/**
 * 怪物技能配置
 * 包含所有怪物可用的技能
 */
import type { SkillConfig } from '@/types'
import { SkillEffectType, Element } from '@/types'

/** 怪物技能配置 */
export const monsterSkillConfigs: SkillConfig[] = [
  // ===== 史莱姆技能 =====
  {
    id: 'slime_jump',
    name: '跳跃攻击',
    description: '跳跃砸向敌人',
    icon: '💚',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 1.3,
    cooldown: 5000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'slime_split',
    name: '分裂',
    description: '分裂攻击周围的敌人',
    icon: '💚',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.5,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },

  // ===== 巨鼠技能 =====
  {
    id: 'rat_bite',
    name: '撕咬',
    description: '锋利的撕咬',
    icon: '🐀',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 1.2,
    cooldown: 3000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'rat_swarm',
    name: '鼠群围攻',
    description: '召集鼠群攻击所有敌人',
    icon: '🐀',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.8,
    cooldown: 10000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },

  // ===== 灰狼技能 =====
  {
    id: 'wolf_howl',
    name: '狼嚎',
    description: '发出威慑的嚎叫，提升攻击力',
    icon: '🐺',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Physical,
    value: 0.2,
    cooldown: 12000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1,
    buffs: [{ stat: 'attack', value: 0.2, isPercent: true, duration: 5000 }]
  },
  {
    id: 'wolf_pack',
    name: '狼群围攻',
    description: '协同狼群攻击所有敌人',
    icon: '🐺',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 1.0,
    cooldown: 10000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },

  // ===== 骷髅兵技能 =====
  {
    id: 'bone_strike',
    name: '骨击',
    description: '用骨头猛击敌人',
    icon: '💀',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 1.3,
    cooldown: 4000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'skeleton_army',
    name: '骷髅军团',
    description: '召唤骷髅军团攻击所有敌人',
    icon: '💀',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.9,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },

  // ===== 哥布林技能 =====
  {
    id: 'goblin_throw',
    name: '投掷石块',
    description: '向敌人投掷石块',
    icon: '👺',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 1.2,
    cooldown: 3000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'goblin_swarm',
    name: '哥布林群攻',
    description: '一群哥布林围攻所有敌人',
    icon: '👺',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.7,
    cooldown: 10000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },

  // ===== 毒蜘蛛技能 =====
  {
    id: 'poison_bite',
    name: '毒咬',
    description: '带有毒素的撕咬',
    icon: '🦂',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Poison,
    value: 1.2,
    cooldown: 4000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1,
    dot: { damage: 5, interval: 2000, duration: 6000 }
  },
  {
    id: 'web',
    name: '蛛网',
    description: '喷射蛛网减速敌人',
    icon: '🕸️',
    effectType: SkillEffectType.Debuff,
    target: 'single',
    element: Element.Physical,
    value: 0.3,
    cooldown: 8000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2,
    buffs: [{ stat: 'speed', value: -0.3, isPercent: true, duration: 3000 }]
  },
  {
    id: 'spider_swarm',
    name: '蜘蛛群袭',
    description: '召唤蜘蛛群攻击所有敌人',
    icon: '🕷️',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.8,
    cooldown: 12000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 3
  },

  // ===== 火焰小鬼技能 =====
  {
    id: 'fireball',
    name: '火球',
    description: '发射火球攻击敌人',
    icon: '🔥',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Fire,
    value: 1.4,
    cooldown: 4000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'fire_shield',
    name: '火焰护盾',
    description: '点燃火焰护盾提升防御',
    icon: '🔥',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Fire,
    value: 0.2,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2,
    buffs: [{ stat: 'defense', value: 0.2, isPercent: true, duration: 8000 }]
  },
  {
    id: 'inferno',
    name: '地狱火',
    description: '召唤地狱火轰炸所有敌人',
    icon: '🔥',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Fire,
    value: 1.8,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 3
  },

  // ===== 冰狼技能 =====
  {
    id: 'ice_bite',
    name: '冰咬',
    description: '附带寒气的撕咬，有几率冻结目标',
    icon: '🐺',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Ice,
    value: 1.3,
    cooldown: 4000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1,
    buffs: [{ stat: 'speed', value: -0.15, isPercent: true, duration: 3000 }]
  },
  {
    id: 'frost_howl',
    name: '霜嚎',
    description: '发出冰霜嚎叫，冻结所有敌人',
    icon: '🐺',
    effectType: SkillEffectType.Debuff,
    target: 'all',
    element: Element.Ice,
    value: 0.5,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2,
    buffs: [{ stat: 'speed', value: -0.4, isPercent: true, duration: 4000 }]
  },
  {
    id: 'blizzard',
    name: '暴风雪',
    description: '召唤暴风雪攻击所有敌人',
    icon: '❄️',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Ice,
    value: 1.5,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 3,
    buffs: [{ stat: 'speed', value: -0.3, isPercent: true, duration: 5000 }]
  },

  // ===== 魔龙技能 =====
  {
    id: 'dragon_breath',
    name: '龙息',
    description: '喷吐龙息，灼烧所有敌人',
    icon: '🐉',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Fire,
    value: 1.5,
    cooldown: 8000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2,
    dot: { damage: 8, interval: 2000, duration: 8000 }
  },
  {
    id: 'tail_sweep',
    name: '扫尾',
    description: '用巨尾横扫所有敌人，有几率眩晕',
    icon: '🐉',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 1.2,
    cooldown: 8000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 3,
    buffs: [{ stat: 'speed', value: -0.2, isPercent: true, duration: 3000 }]
  },
  {
    id: 'dragon_rage',
    name: '龙怒',
    description: '进入暴怒状态，大幅提升攻击力',
    icon: '🐉',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Fire,
    value: 0.3,
    cooldown: 20000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 4,
    buffs: [{ stat: 'attack', value: 0.3, isPercent: true, duration: 10000 }]
  },

  // ===== 深渊技能 =====
  {
    id: 'shadow_strike',
    name: '暗影突袭',
    description: '从暗影中突袭，造成高额伤害',
    icon: '🌑',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Dark,
    value: 1.8,
    cooldown: 6000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'void_bolt',
    name: '虚空之箭',
    description: '发射虚空能量箭矢',
    icon: '🌑',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Dark,
    value: 1.5,
    cooldown: 5000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1,
    dot: { damage: 10, interval: 2000, duration: 8000 }
  },
  {
    id: 'dark_nova',
    name: '暗影新星',
    description: '引爆暗影能量，伤害所有敌人',
    icon: '🌑',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Dark,
    value: 1.6,
    cooldown: 12000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },
  {
    id: 'abyss_drain',
    name: '深渊吞噬',
    description: '吞噬敌人生命力回复自身',
    icon: '🌑',
    effectType: SkillEffectType.Drain,
    target: 'single',
    element: Element.Dark,
    value: 1.4,
    cooldown: 8000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },
  {
    id: 'shadow_clones',
    name: '影分身',
    description: '召唤影分身攻击所有敌人',
    icon: '🌑',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Dark,
    value: 1.2,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 3
  },
  {
    id: 'void_rift',
    name: '虚空裂隙',
    description: '撕裂空间，释放虚空能量',
    icon: '🌑',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Dark,
    value: 2.0,
    cooldown: 20000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 4,
    buffs: [{ stat: 'defense', value: -0.2, isPercent: true, duration: 6000 }]
  },

  // ===== 神界技能 =====
  {
    id: 'holy_slash',
    name: '神圣斩击',
    description: '以神圣之力斩击敌人',
    icon: '✨',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Holy,
    value: 1.6,
    cooldown: 5000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 1
  },
  {
    id: 'divine_judgment',
    name: '神圣审判',
    description: '降下神罚，对单个敌人造成巨额伤害',
    icon: '⚡',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Holy,
    value: 2.0,
    cooldown: 10000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2
  },
  {
    id: 'celestial_storm',
    name: '星暴',
    description: '召唤星辰风暴轰炸所有敌人',
    icon: '🌟',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Holy,
    value: 1.8,
    cooldown: 15000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 3
  },
  {
    id: 'angelic_barrier',
    name: '天使屏障',
    description: '展开天使屏障，大幅提升防御',
    icon: '🛡️',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Holy,
    value: 0.4,
    cooldown: 18000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 2,
    buffs: [
      { stat: 'defense', value: 0.3, isPercent: true, duration: 8000 },
      { stat: 'magicDefense', value: 0.3, isPercent: true, duration: 8000 }
    ]
  },
  {
    id: 'holy_resurrection',
    name: '圣光复活',
    description: '以圣光治愈自身',
    icon: '💫',
    effectType: SkillEffectType.Heal,
    target: 'self',
    element: Element.Holy,
    value: 0.3,
    cooldown: 20000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 4
  },
  {
    id: 'wrath_of_god',
    name: '神之震怒',
    description: '释放神之力量毁灭一切',
    icon: '👑',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Holy,
    value: 2.5,
    cooldown: 25000,
    mpCost: 0,
    unlockLevel: 1,
    priority: 5,
    buffs: [{ stat: 'attack', value: -0.3, isPercent: true, duration: 5000 }]
  }
]
