/**
 * 玩家技能配置
 * 包含通用技能和三职业的专属技能
 */
import type { SkillConfig } from '@/types'
import { SkillEffectType, Element, CharacterClass } from '@/types'

/** 玩家技能配置 */
export const playerSkillConfigs: SkillConfig[] = [
  // ===== 通用技能 =====
  {
    id: 'attack',
    name: '普通攻击',
    description: '进行一次普通攻击',
    icon: '⚔️',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 1.0,
    cooldown: 0,
    mpCost: 0,
    unlockLevel: 1,
    priority: 0
  },

  // ===== 战士技能 =====
  {
    id: 'warrior_slash',
    name: '猛力斩击',
    description: '强力的斩击，造成150%物理伤害',
    icon: '🗡️',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 1.5,
    cooldown: 3000,
    mpCost: 10,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Warrior],
    priority: 2
  },
  {
    id: 'warrior_whirlwind',
    name: '旋风斩',
    description: '旋转攻击所有敌人，造成80%物理伤害',
    icon: '🌀',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.8,
    cooldown: 8000,
    mpCost: 25,
    unlockLevel: 10,
    classRestriction: [CharacterClass.Warrior],
    priority: 3
  },
  {
    id: 'warrior_battle_cry',
    name: '战吼',
    description: '发出战吼，提升自身攻击力20%，持续10秒',
    icon: '📢',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Physical,
    value: 0.2,
    cooldown: 30000,
    mpCost: 15,
    unlockLevel: 20,
    classRestriction: [CharacterClass.Warrior],
    priority: 4,
    buffs: [{ stat: 'attack', value: 0.2, isPercent: true, duration: 10000 }]
  },
  {
    id: 'warrior_execute',
    name: '处决',
    description: '对血量低于30%的敌人造成300%伤害',
    icon: '⚔️',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 3.0,
    cooldown: 15000,
    mpCost: 30,
    unlockLevel: 30,
    classRestriction: [CharacterClass.Warrior],
    priority: 5
  },
  {
    id: 'warrior_heroic_strike',
    name: '英雄打击',
    description: '倾注全力的一击，造成400%物理伤害并恢复自身20%最大生命值',
    icon: '💎',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 4.0,
    cooldown: 20000,
    mpCost: 50,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Warrior],
    advanceRestriction: 5,
    priority: 6
  },
  {
    id: 'warrior_dragon_charge',
    name: '龙骑冲锋',
    description: '化龙突进，对单体造成350%伤害并击晕3秒',
    icon: '🐲',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 3.5,
    cooldown: 18000,
    mpCost: 60,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Warrior],
    advanceRestriction: 6,
    priority: 7,
    buffs: [{ stat: 'speed', value: -1, isPercent: true, duration: 3000 }]
  },
  {
    id: 'warrior_sword_aura',
    name: '剑气纵横',
    description: '释放剑气风暴，对全体敌人造成200%物理伤害，降低其防御20%持续8秒',
    icon: '⚡',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 2.0,
    cooldown: 15000,
    mpCost: 70,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Warrior],
    advanceRestriction: 7,
    priority: 8,
    buffs: [{ stat: 'defense', value: -0.2, isPercent: true, duration: 8000 }]
  },
  {
    id: 'warrior_war_god_mode',
    name: '武神降临',
    description: '进入武神形态，10秒内攻击力+100%且每次攻击回复5%生命值',
    icon: '⛩️',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Physical,
    value: 1.0,
    cooldown: 60000,
    mpCost: 100,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Warrior],
    advanceRestriction: 8,
    priority: 9,
    buffs: [{ stat: 'attack', value: 1.0, isPercent: true, duration: 10000 }]
  },
  {
    id: 'warrior_ultimate_slash',
    name: '灭世斩',
    description: '毁天灭地的一击，对单体造成600%物理伤害，无视50%防御',
    icon: '💀',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 6.0,
    cooldown: 30000,
    mpCost: 150,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Warrior],
    advanceRestriction: 9,
    priority: 10
  },

  // ===== 法师技能 =====
  {
    id: 'mage_fireball',
    name: '火球术',
    description: '发射一个火球，造成150%魔法伤害并灼烧目标',
    icon: '🔥',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Fire,
    value: 1.5,
    cooldown: 2000,
    mpCost: 4,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Mage],
    priority: 2,
    dot: { damage: 5, interval: 2000, duration: 6000 }
  },
  {
    id: 'mage_heal',
    name: '治愈术',
    description: '恢复自身100点生命值',
    icon: '💚',
    effectType: SkillEffectType.Heal,
    target: 'self',
    element: Element.Physical,
    value: 100,
    cooldown: 8000,
    mpCost: 30,
    unlockLevel: 5,
    classRestriction: [CharacterClass.Mage],
    priority: 3
  },
  {
    id: 'mage_meteor',
    name: '陨石术',
    description: '召唤陨石轰炸所有敌人，造成120%魔法伤害并灼烧',
    icon: '☄️',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Fire,
    value: 1.2,
    cooldown: 10000,
    mpCost: 9,
    unlockLevel: 15,
    classRestriction: [CharacterClass.Mage],
    priority: 4,
    dot: { damage: 8, interval: 2000, duration: 8000 }
  },
  {
    id: 'mage_frost_nova',
    name: '冰霜新星',
    description: '释放冰霜能量，对全体敌人造成100%魔法伤害并减速',
    icon: '❄️',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Ice,
    value: 1.0,
    cooldown: 12000,
    mpCost: 15,
    unlockLevel: 25,
    classRestriction: [CharacterClass.Mage],
    priority: 5,
    buffs: [{ stat: 'speed', value: -0.2, isPercent: true, duration: 3000 }]
  },
  {
    id: 'mage_arcane_blast',
    name: '奥术冲击',
    description: '释放奥术能量，造成250%魔法伤害',
    icon: '💫',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Physical,
    value: 2.5,
    cooldown: 8000,
    mpCost: 22,
    unlockLevel: 35,
    classRestriction: [CharacterClass.Mage],
    advanceRestriction: 4,
    priority: 6
  },
  {
    id: 'mage_elemental_storm',
    name: '元素风暴',
    description: '召唤四元素风暴，对全体造成180%魔法伤害并施加随机元素DOT',
    icon: '🌪️',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Fire,
    value: 1.8,
    cooldown: 12000,
    mpCost: 65,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Mage],
    advanceRestriction: 6,
    priority: 7,
    dot: { damage: 15, interval: 2000, duration: 10000 }
  },
  {
    id: 'mage_absolute_barrier',
    name: '绝对壁垒',
    description: '展开魔法屏障，10秒内免疫所有伤害',
    icon: '🛡️',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Physical,
    value: 0.99,
    cooldown: 90000,
    mpCost: 80,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Mage],
    advanceRestriction: 7,
    priority: 8,
    buffs: [{ stat: 'defense', value: 0.99, isPercent: true, duration: 10000 }]
  },
  {
    id: 'mage_time_stop',
    name: '时间停止',
    description: '冻结时间流逝，全体敌人停止行动5秒，期间受到300%魔法伤害',
    icon: '⏳',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Physical,
    value: 3.0,
    cooldown: 45000,
    mpCost: 120,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Mage],
    advanceRestriction: 8,
    priority: 9,
    buffs: [{ stat: 'speed', value: -0.99, isPercent: true, duration: 5000 }]
  },
  {
    id: 'mage_omniscience',
    name: '全知全能',
    description: '引爆全部魔力，对全体造成500%魔法伤害，无视所有抗性',
    icon: '👑',
    effectType: SkillEffectType.MagicDamage,
    target: 'all',
    element: Element.Physical,
    value: 5.0,
    cooldown: 60000,
    mpCost: 200,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Mage],
    advanceRestriction: 9,
    priority: 10
  },

  // ===== 游侠技能 =====
  {
    id: 'ranger_double_shot',
    name: '双箭射击',
    description: '射出两支箭，每支造成80%物理伤害',
    icon: '🏹',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 0.8,
    cooldown: 3000,
    mpCost: 12,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Ranger],
    priority: 2
  },
  {
    id: 'ranger_evade',
    name: '疾风步',
    description: '提升自身闪避率30%，持续5秒',
    icon: '💨',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Physical,
    value: 0.3,
    cooldown: 20000,
    mpCost: 15,
    unlockLevel: 8,
    classRestriction: [CharacterClass.Ranger],
    priority: 3,
    buffs: [{ stat: 'dodge', value: 0.3, isPercent: true, duration: 5000 }]
  },
  {
    id: 'ranger_multi_shot',
    name: '多重射击',
    description: '射出多支箭矢，攻击所有敌人，造成60%物理伤害',
    icon: '🎯',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 0.6,
    cooldown: 8000,
    mpCost: 25,
    unlockLevel: 12,
    classRestriction: [CharacterClass.Ranger],
    priority: 4
  },
  {
    id: 'ranger_aimed_shot',
    name: '瞄准射击',
    description: '精心瞄准的一击，造成200%物理伤害',
    icon: '🎯',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 2.0,
    cooldown: 6000,
    mpCost: 20,
    unlockLevel: 20,
    classRestriction: [CharacterClass.Ranger],
    priority: 5
  },
  {
    id: 'ranger_arrow_rain',
    name: '箭雨',
    description: '召唤箭雨，对全体敌人造成150%物理伤害',
    icon: '🏹',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 1.5,
    cooldown: 15000,
    mpCost: 45,
    unlockLevel: 35,
    classRestriction: [CharacterClass.Ranger],
    advanceRestriction: 4,
    priority: 6
  },
  {
    id: 'ranger_shadow_strike',
    name: '暗影突袭',
    description: '从暗影中现身，对单体造成320%伤害且必定暴击',
    icon: '🌑',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'single',
    element: Element.Physical,
    value: 3.2,
    cooldown: 12000,
    mpCost: 55,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Ranger],
    advanceRestriction: 6,
    priority: 7
  },
  {
    id: 'ranger_wind_walk',
    name: '风之漫步',
    description: '化身为风，8秒内闪避率+50%，攻击速度翻倍',
    icon: '🌀',
    effectType: SkillEffectType.BuffSelf,
    target: 'self',
    element: Element.Physical,
    value: 0.5,
    cooldown: 30000,
    mpCost: 70,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Ranger],
    advanceRestriction: 7,
    priority: 8,
    buffs: [
      { stat: 'dodge', value: 0.5, isPercent: true, duration: 8000 },
      { stat: 'speed', value: 1.0, isPercent: true, duration: 8000 }
    ]
  },
  {
    id: 'ranger_hunters_mark',
    name: '猎魔印记',
    description: '标记目标，10秒内对其伤害+50%，并持续造成流血伤害',
    icon: '👁️',
    effectType: SkillEffectType.MagicDamage,
    target: 'single',
    element: Element.Physical,
    value: 2.0,
    cooldown: 20000,
    mpCost: 90,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Ranger],
    advanceRestriction: 8,
    priority: 9,
    dot: { damage: 25, interval: 1500, duration: 10000 },
    buffs: [{ stat: 'defense', value: -0.3, isPercent: true, duration: 10000 }]
  },
  {
    id: 'ranger_phantom_arrow',
    name: '幻影穿云',
    description: '射出穿透幻影箭，对全体造成400%物理伤害，不可闪避',
    icon: '🌈',
    effectType: SkillEffectType.PhysicalDamage,
    target: 'all',
    element: Element.Physical,
    value: 4.0,
    cooldown: 35000,
    mpCost: 140,
    unlockLevel: 1,
    classRestriction: [CharacterClass.Ranger],
    advanceRestriction: 9,
    priority: 10
  }
]
